services:
  nicehash:
    image: dockerhubnh/nicehash:latest
    environment:
      MINING_ADDRESS: "YOUR_MINING_ADDRESS"
      MINING_WORKER_NAME: "rig-WORKER_NAME"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always