services:
  nicehash:
    build: .
    image: nicehash
    container_name: nicehash
    env_file:
      - nicehash.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always